name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-go:
    name: Build Go implementation
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out project files
        uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          cd go
          export PATH=$PATH:$(go env GOPATH)/bin
          make PACKAGE=quorum-plugin-hello-world-go VERSION=${{ steps.meta.outputs.version_short }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: go-artifacts
          path: go/build
  build-java:
    name: Build Java implementation
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Check out project files
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Load cached dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        id: build
        run: |
          cd java
          mvn clean package -Dpackage=quorum-plugin-hello-world-java -Dversion=${{ steps.meta.outputs.version_short }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: java-artifacts
          path: java/target/dist
  deploy:
    name: Deploy ${{ matrix.artifact }}
    needs:
      - build-go
      - build-java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact: ["go-artifacts", "java-artifacts"]
    steps:
      - name: Setup Cloudsmith Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: cloudsmith # this server id is in the generated pom.xml used to run `mvn deploy`
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Download artifacts
        uses: actions/download-artifact@v1
        # inside ${{ matrix.artifact }} folder, there are:
        # - plugin-meta.json
        # - <os>-<arch> folders
        # - the zip and sha256 files for each <os>-<arch>
        with:
          name: ${{ matrix.artifact }}
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=plugin_name::$(cat ${{ matrix.artifact }}/plugin-meta.json | jq -r .name)"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Upload to Cloudsmith
        working-directory: ${{ matrix.artifact }}
        run: |-
          curl -1sLf 'https://artifacts.consensys.net/public/quorum-go-plugins/raw/names/utils/versions/latest/uploader.sh' \
            | bash -s ./ ${{ steps.meta.outputs.plugin_name }} ${{ steps.meta.outputs.version_short }} linux-amd64 darwin-amd64
        env:
          MAVEN_USERNAME: '${{ secrets.CLOUDSMITH_USERNAME }}'
          MAVEN_PASSWORD: '${{ secrets.CLOUDSMITH_API_KEY }}'
  notify:
    name: Notify Slack
    needs:
      - deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Slack message
        id: status
        uses: actions/github-script@0.8.0
        with:
          script: |
            ////////////////////////////////////
            // retrieve workflow run data
            ////////////////////////////////////

            console.log("get workflow run")
            const wf_run = await github.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.run_id }}
            })
            console.log("get jobs for workflow run:", wf_run.data.jobs_url)
            const jobs_response = await github.request(wf_run.data.jobs_url)

            ////////////////////////////////////
            // build slack notification message
            ////////////////////////////////////

            // some utility functions
            var date_diff_func = function(start, end) {
                var duration = end - start
                // format the duration
                var delta = duration / 1000
                var days = Math.floor(delta / 86400)
                delta -= days * 86400
                var hours = Math.floor(delta / 3600) % 24
                delta -= hours * 3600
                var minutes = Math.floor(delta / 60) % 60
                delta -= minutes * 60
                var seconds = Math.floor(delta % 60)
                var format_func = function(v, text, check) {
                    if (v <= 0 && check) {
                        return ""
                    } else {
                        return v + text
                    }
                }
                return format_func(days, "d", true) + format_func(hours, "h", true) + format_func(minutes, "m", true) + format_func(seconds, "s", false)
            }
            var status_icon_func = function(s) {
                switch (s) {
                case "success":
                    return ":white_check_mark:"
                case "failure":
                    return ":no_entry:"
                default:
                    return ":z:"
                }
            }
            const commit = "${{ github.sha }}".substr(0, 6)

            // build the message
            var fields = []
            var workflow_status = "success"
            for (j of jobs_response.data.jobs) {
                console.log(j.name, ":", j.status, j.conclusion, j.started_at, j.completed_at)
                // ignore the current job running this script
                if (j.status != "completed") {
                    continue
                }
                if (j.conclusion == "failure") {
                    workflow_status = "failure"
                }
                fields.push({
                    type: "mrkdwn",
                    text: status_icon_func(j.conclusion) + " <" + j.html_url + "|*" + j.name + "*>\n   \u21b3 completed in " + date_diff_func(new Date(j.started_at), new Date(j.completed_at))
                })
            }

            var slack_msg = {
                blocks: [
                    {
                        type: "section",
                        text: {
                            type: "mrkdwn",
                            text: "<https://github.com/${{ github.repository }}|*${{ github.repository }}*>\nfrom *${{ github.ref }}@" + commit + "*"
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "mrkdwn",
                            text: status_icon_func(workflow_status) + " *${{ github.workflow }}*\nWorkflow run <" + wf_run.data.html_url + "|#${{ github.run_number }}> completed in " + date_diff_func(new Date(wf_run.data.created_at), new Date(wf_run.data.updated_at))
                        }
                    },
                    {
                        type: "divider"
                    },
                    {
                        type: "section",
                        fields: fields
                    }
                ]
            }
            return slack_msg
      - name: Send to Slack
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '${{ steps.status.outputs.result }}'